In [0]:
import numpy as np

#### Create Rank 1 numpy array

In [0]:
an_array = np.array([3, 33, 333])

In [0]:
print(type(an_array))
print(an_array.shape)

<class 'numpy.ndarray'>
(3,)


In [0]:
print(an_array)

[  3  33 333]


In [0]:
print(an_array[0], an_array[1], an_array[2])

3 33 333


In [0]:
an_array[0] = 888
print(an_array)

[888  33 333]


#### Create Rank 2 numpy array

In [0]:
another = np.array([[11, 12, 13], [21, 22, 23]])
print(another)

[[11 12 13]
 [21 22 23]]


In [0]:
another.shape

(2, 3)

In [0]:
print(another[0,0])
print(another[0,1])
print(another[1,0])

11
12
21


#### Other ways of creating numpy arrays

In [0]:
# 2x2 array of zeros
ex1 = np.zeros((2,2))
print(ex1.shape)
print(ex1)

(2, 2)
[[0. 0.]
 [0. 0.]]


In [0]:
# 2x2 array filled with 'some-value'
ex2 = np.full((2,2), 9.0)
print(ex2)

[[9. 9.]
 [9. 9.]]


In [0]:
# 2x2 identity matrix (diagonals 1, rest 0)
ex3 = np.eye(2,2)
print(ex3)

[[1. 0.]
 [0. 1.]]


In [0]:
# 1x2 array of ones
ex4 = np.ones((1,2))
print(ex4)
print(ex4.shape)

# above array is actually a two-dimensional or Rank 2. We need to specify both - row & column, to access an element.
print(ex4[0,1])

[[1. 1.]]
(1, 2)
1.0


In [0]:
# create an array of random floats b/w 0 & 1 - [0,1)
ex5 = np.random.random((2,2))
print(ex5)

[[0.1000848  0.25112568]
 [0.63697944 0.94700791]]


In [0]:
# to get the same values everytime
# we can set seed before using random function.
np.random.seed(1)
ex5 = np.random.random((2,2))
print(ex5)

[[4.17022005e-01 7.20324493e-01]
 [1.14374817e-04 3.02332573e-01]]


## Array indexing

### Slice Indexing

In [0]:
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array.shape)
print(an_array)

(3, 4)
[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [0]:
a_slice = an_array[0:2, 1:3]
print(a_slice)

[[12 13]
 [22 23]]


#### When we modify a slice, the underlying array also gets modified.

In [0]:
print("Before:", an_array[0,1])
a_slice[0,0] = 1000
print("After:", an_array[0,1])

Before: 12
After: 1000


In [0]:
print(an_array)

[[  11 1000   13   14]
 [  21   22   23   24]
 [  31   32   33   34]]


In [0]:
print(a_slice)

[[1000   13]
 [  22   23]]


#### To avoid such scenario, use copy() function to create a copy or slice of any array.

In [0]:
an_array = np.array([[11, 12, 13, 14],
                     [21, 22, 23, 24],
                     [31, 32, 33, 34]])
a_slice = an_array[0:2, 1:3].copy()

print(an_array)
print(a_slice)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]
[[12 13]
 [22 23]]


In [0]:
a_slice[0,0] = 800

print(a_slice)
print(an_array)

[[800  13]
 [ 22  23]]
[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [0]:
# create a slice of an_array which will have 11,13,31,33.
b_slice = an_array[[0,2],:][:,[0,2]].copy()
print(b_slice)

[[11 13]
 [31 33]]


### Use both integer indexing and slice indexing

In [0]:
an_array = np.array([[11,12,13,14],
                     [21,22,23,24],
                     [31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


Using both indexing will always result in a lower Rank array.

In [0]:
row_rank1 = an_array[1, :]
print(row_rank1, row_rank1.shape)

[21 22 23 24] (4,)


If we used slice indexing only, we would have got Rank 2 array only.

In [0]:
row_rank2 = an_array[1:2, :]
print(row_rank2, row_rank2.shape)

[[21 22 23 24]] (1, 4)


This is similar for columns as well.

In [0]:
col_rank1 = an_array[:, 1]
col_rank2 = an_array[:, 1:2]

print(col_rank1, col_rank1.shape)
print()
print(col_rank2, col_rank2.shape)

[12 22 32] (3,)

[[12]
 [22]
 [32]] (3, 1)


## Boolean Indexing

### Array Indexing for changing elements

In [5]:
an_array = np.array([[11, 12],
                     [21, 22],
                     [31, 32]])
print(an_array)

[[11 12]
 [21 22]
 [31 32]]


In [6]:
# creating a fliter which will be boolean values for whether each element meets the condition.
filter_ = (an_array > 15)
print(filter_)

[[False False]
 [ True  True]
 [ True  True]]


In [7]:
# we can now select just those elements which meet the criterion
print(an_array[filter_])

[21 22 31 32]


We can do this directly putting the filtering condition with array call.

In [10]:
# filter values which are greater than 20 and lesser than 30
print(an_array[(an_array>20) & (an_array<30)])

[21 22]


In [14]:
a_slice = an_array[(an_array<20)]
# a_slice[0] = 100
print(a_slice)
print(an_array)

[11 12]
[[11 12]
 [21 22]
 [31 32]]


In [15]:
print(id(a_slice))
print(id(an_array))

139928716669056
139928716602064


What's particulary useful is that we can actually change elements in the array applying a similar logical filter.

In [16]:
# Let's add 100 to all even values of an_array
an_array[an_array%2 == 0] += 100
print(an_array)

[[ 11 112]
 [ 21 122]
 [ 31 132]]


## <font color='violet'>Datatypes and Array Operations</font>

### <font color='lightblue'>Datatypes:</font>

#### Python implicitly assigns data types

In [17]:
ex1 = np.array([11, 12])
print(ex1.dtype)

int64


In [18]:
ex2 = np.array([11.0, 12.0])
print(ex2.dtype)

float64


#### We can explicilty assing data types as well.

In [20]:
ex3 = np.array([11, 12], dtype=np.float64)
print(ex3.dtype)

float64


In [21]:
ex3 = np.array([11, 12], dtype=np.int32)
print(ex3.dtype)

int32


We can infact use this to force floats into integers

In [23]:
ex4 = np.array([11.1, 12.7], dtype=np.int64)
print(ex4.dtype)
print(ex4)

int64
[11 12]


### <font color='lightblue'>Arithmetic Array operations</font>

In [34]:
x = np.array([[111, 112], [121, 122]], dtype=np.int64)
y = np.array([[211.1, 212.1], [221.1, 222.1]], dtype=np.float64)
print(x)
print(y)

[[111 112]
 [121 122]]
[[211.1 212.1]
 [221.1 222.1]]


In [25]:
# Add
print(x+y)
print(np.add(x,y))

[[322.1 324.1]
 [342.1 344.1]]
[[322.1 324.1]
 [342.1 344.1]]


In [26]:
# Subtract
print(np.subtract(x,y))

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [27]:
# Multiply
print(np.multiply(x,y))

[[23432.1 23755.2]
 [26753.1 27096.2]]


In [28]:
# Divide
print(np.divide(x,y))

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]


In [33]:
# Square-root
print(np.sqrt(x))
# np.sqrt?

[[10.53565375 10.58300524]
 [11.         11.04536102]]


In [35]:
# Exponent (e ** x)
print(np.exp(x))

[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]


In [36]:
# Matirx multiplication
print(np.matmul(x,y))

[[48195.3 48418.3]
 [52517.3 52760.3]]


## <font color='violet'>Set Operations</font>

### <font color='lightblue'>Basic Statistical Operations</font>

In [40]:
np.random.seed(1)
arr = 10 * np.random.randn(2,5)
print(arr)

[[ 16.24345364  -6.11756414  -5.28171752 -10.72968622   8.65407629]
 [-23.01538697  17.44811764  -7.61206901   3.19039096  -2.49370375]]


In [42]:
# Compute mean of all elements
print(arr.mean())

-0.9714089080609984


In [43]:
# mean by row
print(arr.mean(axis=1))

[ 0.55371241 -2.49653023]


In [44]:
# mean by column
print(arr.mean(axis=0))

[-3.38596667  5.66527675 -6.44689327 -3.76964763  3.08018627]


In [45]:
# mean of all elements
print(arr.sum())
print(np.sum(arr))

-9.714089080609984
-9.714089080609984


In [46]:
# median across rows
print(np.median(arr, axis=1))
print()
print(np.median(arr, axis=0))

[-5.28171752 -2.49370375]

[-3.38596667  5.66527675 -6.44689327 -3.76964763  3.08018627]


### <font color='lightblue'>Sorting</font>

In [48]:
np.random.seed(50)
unsorted = np.random.randn(10)
print(unsorted)

[-1.56035211 -0.0309776  -0.62092842 -1.46458049  1.41194612 -0.47673214
 -0.78046921  1.07026774 -1.2822926  -1.3274789 ]


In [49]:
# create a copy and sort
sorted_ = np.array(unsorted)
sorted_.sort()
print(sorted_)

[-1.56035211 -1.46458049 -1.3274789  -1.2822926  -0.78046921 -0.62092842
 -0.47673214 -0.0309776   1.07026774  1.41194612]


In [56]:
# reverse sort
sorted_[::-1].sort()
print(sorted_)

[ 1.41194612  1.07026774 -0.0309776  -0.47673214 -0.62092842 -0.78046921
 -1.2822926  -1.3274789  -1.46458049 -1.56035211]


### <font color='lightblue'>Finding Unique Elements</font>

In [57]:
array = np.array([1, 2, 4, 4, 2, 1, 3, 7])
print(array)
print()
print(np.unique(array))

[1 2 4 4 2 1 3 7]

[1 2 3 4 7]


### <font color='lightblue'>Set Operations with np.array data type</font>

In [58]:
s1 = np.array(['desk', 'chair', 'bulb'])
s2 = np.array(['lamp', 'bulb', 'chair'])
print(s1,s2)

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [59]:
# Intersection 1d
print(np.intersect1d(s1, s2))

['bulb' 'chair']


In [60]:
# Union 1d
print(np.union1d(s1, s2))

['bulb' 'chair' 'desk' 'lamp']


In [61]:
# Set difference 1d
print(np.setdiff1d(s1, s2))

['desk']


In [63]:
# In 1d (which element of s1 in s2)
print(np.in1d(s1, s2))

[False  True  True]
